# Auto-generated by IDE. All changes by user will be lost!
# Created at 24/02/13 8:51 PM

BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH +=  \
    $$BASEDIR/src

SOURCES +=  \
    $$BASEDIR/src/Closer.cpp \
    $$BASEDIR/src/SocialNetworkModel.cpp \
    $$BASEDIR/src/main.cpp

HEADERS +=  \
    $$BASEDIR/src/Closer.hpp \
    $$BASEDIR/src/SocialNetworkModel.h

lupdate_inclusion {
    SOURCES += \
        $$BASEDIR/../assets/*.qml
}

 \
    $${TARGET}.ts

